const assert=require('node:assert/strict');
const {summarize,createTracker}=require('./economics.js');
const run=(mode,premium=false,workflow=false)=>({mode,workflow_snapshot:workflow?{}:null,cost_comparison:{online_usd:premium?.030:.006,local_usd:premium?.024:0,savings_usd:.006,premium_usd:premium?.024:0},prompt:'private prompt never stored'});
const session=summarize([run('hosted'),run('desktop',true,true)],2);
assert.deepEqual({count:session.count,online:session.online,local:session.local,saved:session.saved,premium:session.premium,builds:session.builds},{count:2,online:.036,local:.024,saved:.006,premium:.024,builds:2});
assert.equal(session.types.chat.count,1);assert.equal(session.types.workflow.local,.024);
const rows=new Map(),storage={get length(){return rows.size;},key:i=>[...rows.keys()][i],getItem:k=>rows.get(k),setItem:(k,v)=>rows.set(k,v)};
const first=createTracker(storage,'first');
assert.deepEqual(first.update(session).totals,session);
assert.deepEqual(first.update(session).totals,session,'rerenders replace current aggregate, never duplicate');
assert.doesNotMatch([...rows.values()].join(''),/private|prompt|workflow_snapshot/);
const second=createTracker(storage,'second'),next=summarize([run('desktop')]);
assert.equal(second.update(next).totals.count,3);assert.equal(second.update(next).totals.saved,.012);
assert.equal(first.update(session).totals.count,3,'cross-session update does not overwrite other session');
assert.equal(createTracker(storage,'first').update(session).totals.count,3,'same session key is idempotent');
rows.set('railcall.savings.v1.invalid','not JSON');
rows.set('railcall.savings.v1.negative',JSON.stringify({version:1,totals:{...session,count:-1}}));
assert.equal(second.update(next).totals.count,3,'malformed or invalid history is ignored');
assert.equal(createTracker(null,'none').update(session).available,false);
const broken=createTracker({setItem(){throw Error('storage blocked');}},'blocked').update(session);
assert.equal(broken.available,false);assert.deepEqual(broken.totals,session);
assert.equal(summarize([]).count,0);
console.log('Passed: same-workload totals, premium charges, work types, local-only scenario savings, lifetime idempotency, aggregate privacy, and storage failure handling.');
