const assert = require('node:assert/strict');
const fs = require('node:fs');
const crypto = require('node:crypto');
const { createModel } = require('./model.js');

async function check() {
  const a = createModel();
  a.prepare('Summarize support issues');
  const chat = a.run();
  assert.equal(chat.cost_usd, 0.006);
  assert.equal(chat.cost_comparison.online_usd, 0.006);
  assert.equal(chat.cost_comparison.local_usd, 0);
  assert.equal(chat.cost_comparison.savings_usd, 0.006);
  assert.equal(chat.cost_comparison.premium_usd, 0);
  assert.equal(Object.isFrozen(chat.cost_comparison), true);
  assert.equal(chat.integrity_status, 'unsigned_preview');
  a.makeDraft();
  const v1 = a.save();
  a.setPremium(true); a.setSource('gmail_preview'); a.edit('Every Friday');
  const savedRun = a.run({ saved: true });
  assert.equal(savedRun.workflow_snapshot.premium, false);
  assert.equal(savedRun.cost_comparison.local_usd, 0,'comparison follows saved policy, not current task premium toggle');
  assert.equal(chat.cost_comparison.local_usd, 0,'earlier conversation comparison stays unchanged');
  assert.equal(savedRun.workflow_snapshot.source, 'sample');
  assert.equal(savedRun.workflow_snapshot.trigger, 'On demand in Chat');
  const v2 = a.save();
  assert.equal(v2.version, 2);
  assert.equal(v1.version, 1);
  assert.equal(savedRun.workflow_version, 1);
  const fingerprint = value => crypto.createHash('sha256').update(a.canonical(value)).digest('hex');
  assert.equal(fingerprint(v1), fingerprint(savedRun.workflow_snapshot), 'run retains the exact saved-version fingerprint');
  assert.notEqual(fingerprint(v1), fingerprint(v2), 'new content/version produces a different fingerprint');
  const detachedVersion = a.latestVersion(); detachedVersion.name = 'mutated';
  assert.notEqual(a.latestVersion().name, 'mutated');
  a.decide(savedRun.id, 'reject');
  assert.equal(savedRun.status, 'cancelled_preview');
  assert.equal(savedRun.real_send_performed, false);
  assert.throws(() => a.decide(savedRun.id, 'approve'));
  a.setMode('desktop');
  const premiumRun = a.run({ saved: true });
  assert.equal(premiumRun.cost_usd, 0.024);
  assert.equal(premiumRun.cost_comparison.online_usd, 0.030);
  assert.equal(premiumRun.cost_comparison.local_usd, 0.024);
  assert.equal(premiumRun.cost_comparison.premium_usd, 0.024);
  assert.equal(premiumRun.cost_comparison.reduction_percent, 20);
  a.decide(premiumRun.id, 'approve');
  assert.equal(premiumRun.real_send_performed, false);
  assert.equal(a.credit(), 49.964);
  const priorTask = a.active().id;
  const catalogVersion = a.usePackage('lead-followup');
  assert.notEqual(a.active().id, priorTask);
  assert.equal(catalogVersion.provenance.catalog_id, 'lead-followup');
  assert.equal(a.runForTask().length, 0);
  a.usePackage('short-summary');
  assert.equal(a.active().draft.modules.length, 1);
  assert.equal(a.latestVersion().modules, undefined);
  assert.throws(() => a.usePackage('short-summary'));
  a.save();
  assert.equal(a.latestVersion().modules.length, 1);
  assert.equal(a.state.runs.length, 3);
  assert.equal(a.state.workflows.length, 2);
  assert.equal(a.credit(), 49.964);

  const specimen = JSON.parse(fs.readFileSync('signed-specimen.json', 'utf8'));
  const key = await crypto.webcrypto.subtle.importKey('raw', Buffer.from(specimen.public_key_hex, 'hex'), 'Ed25519', false, ['verify']);
  const verify = payload => crypto.webcrypto.subtle.verify('Ed25519', key, Buffer.from(specimen.signature_hex, 'hex'), Buffer.from(a.canonical(payload)));
  assert.equal(await verify(specimen.payload), true);
  assert.equal(await verify({ ...specimen.payload, cost_usd: '0.999' }), false);

  const html = fs.readFileSync('index.html', 'utf8');
  const controller = ['workspace.js','studio.js','activity.js','marketplace.js','library.js','integrations.js','builder.js'].map(f=>fs.readFileSync(f,'utf8')).join('\n');
  const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]);
  assert.equal(new Set(ids).size, ids.length, 'duplicate HTML ids');
  for (const [, id] of controller.matchAll(/\$\("#([A-Za-z][A-Za-z0-9]*)"\)/g)) assert.ok(ids.includes(id), 'missing target: ' + id);
  for (const [, target] of html.matchAll(/(?:href|src)="\.\/([^"#?]+)"/g)) assert.ok(fs.existsSync(target), 'missing local asset: ' + target);
  for (const [, name] of html.matchAll(/data-dialog="([^"]+)"/g)) assert.ok(['marketplace','ledger'].includes(name) || ids.includes(name + 'Dialog'), 'missing dialog: ' + name);
  for (const [, name] of html.matchAll(/data-view="([^"]+)"/g)) assert.ok(ids.includes(name + 'View'), 'missing view: ' + name);
  assert.match(html, /https:\/\/railhub\.ai\//);
  assert.match(controller, /Look under the hood/);
  assert.match(html, /Check transactions/);
  assert.match(controller, /data-workflow-fingerprint/);
  assert.doesNotMatch(html, /railbhub/i);
  assert.doesNotMatch(html, /id="studioFrame"[^>]*src=/);
  assert.doesNotMatch(controller, /private_key|BEGIN PRIVATE KEY/);
  const studio = createModel();
  const originalTask = studio.active().id;
  studio.seedStudioExamples();
  assert.equal(studio.active().id, originalTask, 'seeding preserves the current conversation');
  assert.equal(studio.state.runs.length, 3);
  assert.equal(studio.state.workflows.length, 3);
  const initialCredit = studio.credit();
  studio.seedStudioExamples();
  assert.equal(studio.state.runs.length, 3, 'opening Studio again does not duplicate sample runs');
  assert.equal(studio.credit(), initialCredit, 'opening Studio does not charge again');
  const waitingRun = studio.state.runs.find(r => r.status === 'awaiting_demo_approval');
  const waitingTrace = studio.trace(waitingRun.id);
  assert.equal(waitingTrace.find(n => n.kind === 'approval').status, 'waiting');
  assert.equal(waitingTrace.find(n => n.kind === 'action').status, 'blocked');
  assert.equal(waitingTrace.reduce((sum, n) => sum + n.cost, 0), waitingRun.cost_usd);
  studio.decide(waitingRun.id, 'approve');
  assert.equal(studio.trace(waitingRun.id).find(n => n.kind === 'action').status, 'completed');
  assert.equal(waitingRun.real_send_performed, false);
  const stoppedRun = studio.state.runs.find(r => r.status === 'cancelled_preview');
  assert.equal(studio.trace(stoppedRun.id).find(n => n.kind === 'action').status, 'skipped');
  const premiumExample = studio.state.runs.find(r => r.steps.some(s => s.executor === 'premium_api'));
  assert.equal(studio.trace(premiumExample.id).find(n => n.kind === 'review').cost, .024);
  assert.equal(studio.trace(premiumExample.id).find(n => n.kind === 'review').route.location, 'external_provider');
  const hasUserRun = createModel(); hasUserRun.prepare('User task'); hasUserRun.run();
  hasUserRun.seedStudioExamples(); assert.equal(hasUserRun.state.runs.length, 1, 'do not seed over existing work');
  for (const [, id] of controller.matchAll(/\$\('#([A-Za-z][A-Za-z0-9]*)'\)/g)) assert.ok(ids.includes(id) || id === 'libraryHash' && controller.includes('id="libraryHash"'), 'missing Studio target: ' + id);
  const events = studio.activityEntries();
  assert.ok(events.some(e=>e.kind==='action.blocked'));
  assert.ok(events.some(e=>e.kind==='approval.requested'));
  assert.ok(events.some(e=>e.kind==='approval.approved'));
  assert.ok(events.some(e=>e.kind==='policy.compute_changed'));
  assert.ok(events.every(e=>!e.kind.startsWith('marketplace.')), 'built-in examples must never claim public Marketplace installs');
  assert.equal(Number(events.reduce((n,e)=>n+(e.cost_usd||0),0).toFixed(6)), Number(studio.state.runs.reduce((n,r)=>n+r.cost_usd,0).toFixed(6)));
  events[0].title='Modified copy'; assert.notEqual(studio.activityEntries()[0].title,'Modified copy');
  assert.equal(Object.isFrozen(studio.state.events[0]),true);
  const replay = a.run({replayRunId:savedRun.id});
  assert.equal(replay.workflow_version,1);
  assert.deepEqual(replay.workflow_snapshot,savedRun.workflow_snapshot);
  assert.deepEqual(replay.input_snapshot,savedRun.input_snapshot);
  assert.equal(replay.mode,savedRun.mode);
  assert.equal(replay.replay_of,savedRun.id);
  const draftModel=createModel();draftModel.recordRequest('First request');draftModel.makeDraft();
  const draftRun=draftModel.run({workflow:true});draftModel.renameDraft('Changed after run');
  const draftReplay=draftModel.run({replayRunId:draftRun.id});
  assert.equal(draftReplay.workflow_version,null);
  assert.deepEqual(draftReplay.workflow_snapshot,draftRun.workflow_snapshot);
  draftModel.recordRequest('Follow-up request');const followup=draftModel.run();
  assert.equal(followup.input_snapshot.prompt,'Follow-up request');
  assert.notEqual(followup.request_id,draftRun.request_id);
  assert.ok(draftModel.activityEntries().some(e=>e.kind==='workflow.renamed'));
  const catalog=JSON.parse(fs.readFileSync('public-catalog.json','utf8'));
  assert.equal(catalog.items.length,47);
  assert.equal(catalog.items.filter(p=>p.type==='workflow').length,12);
  assert.equal(catalog.items.filter(p=>p.type==='module').length,35);
  for(const p of catalog.items){assert.match(p.slug,/^[a-zA-Z0-9_-]+(?:\/[a-zA-Z0-9_-]+)?$/);assert.ok(p.title);assert.ok(p.seller);}
  assert.match(html,/https:\/\/railcall.ai\/marketplace\//);
  assert.doesNotMatch(html,/Curated sample catalog|id="marketplaceDialog"|data-use-package/);
  assert.match(controller,/data-ledger-run/);
  assert.doesNotMatch(html,/id="sharedLibraryDialog"/);
  assert.ok(ids.includes('libraryView'));
  assert.ok(ids.includes('studioMapView'));
  const selectedVersionModel=createModel();selectedVersionModel.prepare('Sample version test');const first=selectedVersionModel.save();selectedVersionModel.edit('Keep it under 100 words');selectedVersionModel.save();
  const chosenRun=selectedVersionModel.run({versionId:first.version_id});assert.deepEqual(chosenRun.workflow_snapshot,first);
  assert.throws(()=>selectedVersionModel.run({versionId:'missing'}));
  const { catalog: integrations } = require('./integrations.js');
  assert.equal(integrations.length, 454);
  assert.equal(new Set(integrations.map(p=>p.id)).size, 454);
  assert.equal(new Set(integrations.map(p=>p.name.toLowerCase())).size, 454);
  assert.deepEqual(['Direct connector','Reachable app','Marketplace extension'].map(type=>integrations.filter(p=>p.type===type).length),[35,412,7]);
  for (const p of integrations) {
    assert.ok(['Direct connector','Reachable app','Marketplace extension'].includes(p.type));
    assert.equal(new URL(p.url).hostname,'railcall.ai');
    assert.ok(p.access.length && p.boundary && p.summary);
  }
  const routingModel=createModel();routingModel.prepare('A complex strategy question');
  assert.equal(routingModel.active().premium,false,'premium routes require explicit permission');
  assert.match(html,/id="heroForm"/);
  assert.match(html,/data-action="toggle-sidebar"/);
  const artifacts=createModel();artifacts.draftArtifact('app','Build a project planner');
  const av=artifacts.saveArtifact();artifacts.toggleArtifactItem(0);artifacts.updateArtifactTitle('Team planner');
  assert.equal(av.items[0].done,false);assert.notEqual(av.title,artifacts.artifactForTask().draft.title);
  assert.equal(artifacts.artifactForTask().versions[0].items[0].done,false,'saved artifacts remain immutable');
  assert.ok(artifacts.activityEntries().some(e=>e.category==='artifact'));
  const {source}=require('./builder.js');const exported=source({...av,title:'<script>alert(1)</script>'});
  assert.doesNotMatch(exported,/<script>/);assert.match(exported,/&lt;script&gt;/);
  artifacts.newTask();assert.equal(artifacts.artifactForTask(),null,'artifact drafts are scoped to their task');
  assert.doesNotMatch(controller,/data-ledger-run="\\'/);
  console.log('Passed: immutable version replay, every request and decision in central ledger, exact cost accounting, 47 real Marketplace listings, signature/tamper checks, and static routes/assets.');
}
check().catch(error => { console.error(error); process.exitCode = 1; });
